- name: configure {{ component }}
  become: yes
  #hosts: "{{ component }}"
  hosts: localhost
  connection: local
  roles: # this will automaticall load folder called roles in current working directory.
  - "{{ component }}"