CART_HOST: cart.backend-{{ env }}.harshavn24.site
USER_HOST: user.backend-{{ env }}.harshavn24.site
RABBITMQ_HOST: rabbitmq-{{ env }}.harshavn24.site
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123