    - name: copy {{ component }} service to system directory
      ansible.builtin.template:
        src: "{{ component }}.service.j2"
        dest: "/etc/systemd/system/{{ component }}.service"

    - name: systemctl daemon reload
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: start and enable {{ component }}
      ansible.builtin.service:
        name: "{{ component }}"
        state: restarted #even app is not running we can restart
        enabled: yes 